kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchest-controller
  labels:
    app.kubernetes.io/part-of: orchest
    app.kubernetes.io/name: orchest-controller
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
