kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchest-controller
subjects:
  - kind: ServiceAccount
    name: orchest-controller
    namespace: orchest
roleRef:
  kind: ClusterRole
  name: orchest-controller
  apiGroup: rbac.authorization.k8s.io