apiVersion: apps/v1
kind: Deployment
metadata:
    name: orchest-controller
    namespace: orchest
    labels:
        app.kubernetes.io/part-of: orchest
        app.kubernetes.io/name: orchest-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app.kubernetes.io/part-of: orchest
        app.kubernetes.io/name: orchest-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: orchest
        app.kubernetes.io/name: orchest-controller
    spec:
      serviceAccountName: orchest-controller
      containers:
      - name: orchest-controller
        image: "docker.io/dadosfera/orchest-controller:v2023.04.2-1.0.3"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        args:
        - --defaultVersion=$(VERSION)
        - --namespace=$(NAMESPACE)

        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VERSION
            value: v2023.04.2
