apiVersion: v1
kind: Service
metadata:
    name: orchest-controller
    namespace: orchest
    labels:
        app.kubernetes.io/part-of: orchest
        app.kubernetes.io/name: orchest-controller
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/part-of: orchest
    app.kubernetes.io/name: orchest-controller