apiVersion: orchest.io/v1alpha1
kind: OrchestCluster
metadata:
  name: cluster-1
  namespace: orchest
spec:
  singleNode: true
  applications:
  - config:
      helm:
        parameters:
        - name: singleNamespace
          value: "true"
    name: argo-workflow
